// Code generated by protoc-gen-go.
// source: github.com/larskluge/babl/protobuf/modules/angusmcleod/main.proto
// DO NOT EDIT!

/*
Package babl_angusmcleod is a generated protocol buffer package.

It is generated from these files:
	github.com/larskluge/babl/protobuf/modules/angusmcleod/main.proto

It has these top-level messages:
*/
package babl_angusmcleod

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import babl "github.com/larskluge/babl/protobuf/messages"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for CoolestModuleEver service

type CoolestModuleEverClient interface {
	IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error)
	Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error)
}

type coolestModuleEverClient struct {
	cc *grpc.ClientConn
}

func NewCoolestModuleEverClient(cc *grpc.ClientConn) CoolestModuleEverClient {
	return &coolestModuleEverClient{cc}
}

func (c *coolestModuleEverClient) IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error) {
	out := new(babl.BinReply)
	err := grpc.Invoke(ctx, "/babl.angusmcleod.CoolestModuleEver/IO", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coolestModuleEverClient) Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error) {
	out := new(babl.Pong)
	err := grpc.Invoke(ctx, "/babl.angusmcleod.CoolestModuleEver/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoolestModuleEver service

type CoolestModuleEverServer interface {
	IO(context.Context, *babl.BinRequest) (*babl.BinReply, error)
	Ping(context.Context, *babl.Empty) (*babl.Pong, error)
}

func RegisterCoolestModuleEverServer(s *grpc.Server, srv CoolestModuleEverServer) {
	s.RegisterService(&_CoolestModuleEver_serviceDesc, srv)
}

func _CoolestModuleEver_IO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.BinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CoolestModuleEverServer).IO(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CoolestModuleEver_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CoolestModuleEverServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _CoolestModuleEver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babl.angusmcleod.CoolestModuleEver",
	HandlerType: (*CoolestModuleEverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IO",
			Handler:    _CoolestModuleEver_IO_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CoolestModuleEver_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
