modules:
  larskluge:
    - babl-build
    - babl-deploy
    - download
    - image-resize
    - render-website
    - s3
    - string-append
    - string-upcase
    - test-fail
  babltester:
    - bar
