// Code generated by protoc-gen-go.
// source: github.com/larskluge/babl/protobuf/modules/mondoreale/main.proto
// DO NOT EDIT!

/*
Package babl_mondoreale is a generated protocol buffer package.

It is generated from these files:
	github.com/larskluge/babl/protobuf/modules/mondoreale/main.proto

It has these top-level messages:
*/
package babl_mondoreale

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import babl "github.com/larskluge/babl/protobuf/messages"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for TextToImage service

type TextToImageClient interface {
	IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error)
	Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error)
}

type textToImageClient struct {
	cc *grpc.ClientConn
}

func NewTextToImageClient(cc *grpc.ClientConn) TextToImageClient {
	return &textToImageClient{cc}
}

func (c *textToImageClient) IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error) {
	out := new(babl.BinReply)
	err := grpc.Invoke(ctx, "/babl.mondoreale.TextToImage/IO", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textToImageClient) Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error) {
	out := new(babl.Pong)
	err := grpc.Invoke(ctx, "/babl.mondoreale.TextToImage/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TextToImage service

type TextToImageServer interface {
	IO(context.Context, *babl.BinRequest) (*babl.BinReply, error)
	Ping(context.Context, *babl.Empty) (*babl.Pong, error)
}

func RegisterTextToImageServer(s *grpc.Server, srv TextToImageServer) {
	s.RegisterService(&_TextToImage_serviceDesc, srv)
}

func _TextToImage_IO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.BinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TextToImageServer).IO(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _TextToImage_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TextToImageServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _TextToImage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babl.mondoreale.TextToImage",
	HandlerType: (*TextToImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IO",
			Handler:    _TextToImage_IO_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TextToImage_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
