// Code generated by bin/module-mapping
// source: babl.proto
// DO NOT EDIT!

package babl

import (
	_ "github.com/larskluge/babl/protobuf/messages"
	babltester "github.com/larskluge/babl/protobuf/modules/babltester"
	larskluge "github.com/larskluge/babl/protobuf/modules/larskluge"
	grpc "google.golang.org/grpc"
)

func NewStringUpcaseClient(cc *grpc.ClientConn) BinaryClient {
	return BinaryClient(larskluge.NewStringUpcaseClient(cc))
}
func RegisterStringUpcaseServer(s *grpc.Server, srv BinaryServer) {
	larskluge.RegisterStringUpcaseServer(s, srv)
}

var Modules = map[string]Component{
	"babltester/bar": Component{Client: func(cc *grpc.ClientConn) BinaryClient {
		return BinaryClient(babltester.NewBarClient(cc))
	}, Server: func(s *grpc.Server, srv BinaryServer) {
		babltester.RegisterBarServer(s, srv)
	}},
	"larskluge/string-upcase": Component{Client: NewStringUpcaseClient, Server: RegisterStringUpcaseServer},
}
