// Code generated by protoc-gen-go.
// source: github.com/larskluge/babl/protobuf/modules/jangler/main.proto
// DO NOT EDIT!

/*
Package babl_jangler is a generated protocol buffer package.

It is generated from these files:
	github.com/larskluge/babl/protobuf/modules/jangler/main.proto

It has these top-level messages:
*/
package babl_jangler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import babl "github.com/larskluge/babl/protobuf/messages"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for BrandonTest service

type BrandonTestClient interface {
	IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error)
	Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error)
}

type brandonTestClient struct {
	cc *grpc.ClientConn
}

func NewBrandonTestClient(cc *grpc.ClientConn) BrandonTestClient {
	return &brandonTestClient{cc}
}

func (c *brandonTestClient) IO(ctx context.Context, in *babl.BinRequest, opts ...grpc.CallOption) (*babl.BinReply, error) {
	out := new(babl.BinReply)
	err := grpc.Invoke(ctx, "/babl.jangler.BrandonTest/IO", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandonTestClient) Ping(ctx context.Context, in *babl.Empty, opts ...grpc.CallOption) (*babl.Pong, error) {
	out := new(babl.Pong)
	err := grpc.Invoke(ctx, "/babl.jangler.BrandonTest/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BrandonTest service

type BrandonTestServer interface {
	IO(context.Context, *babl.BinRequest) (*babl.BinReply, error)
	Ping(context.Context, *babl.Empty) (*babl.Pong, error)
}

func RegisterBrandonTestServer(s *grpc.Server, srv BrandonTestServer) {
	s.RegisterService(&_BrandonTest_serviceDesc, srv)
}

func _BrandonTest_IO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.BinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BrandonTestServer).IO(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BrandonTest_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(babl.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BrandonTestServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BrandonTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babl.jangler.BrandonTest",
	HandlerType: (*BrandonTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IO",
			Handler:    _BrandonTest_IO_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BrandonTest_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
