// Code generated by protoc-gen-go.
// source: main.proto
// DO NOT EDIT!

/*
Package babl is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	BinRequest
	BinReply
	Empty
	Pong
	Meta
	EchoRequest
	EchoResponse
	CancelRequest
*/
package babl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BinRequest struct {
	Stdin      []byte            `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Env        map[string]string `protobuf:"bytes,2,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PayloadUrl string            `protobuf:"bytes,3,opt,name=payloadUrl" json:"payloadUrl,omitempty"`
	Id         uint64            `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	Module     string            `protobuf:"bytes,5,opt,name=module" json:"module,omitempty"`
}

func (m *BinRequest) Reset()                    { *m = BinRequest{} }
func (m *BinRequest) String() string            { return proto.CompactTextString(m) }
func (*BinRequest) ProtoMessage()               {}
func (*BinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BinRequest) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

type BinReply struct {
	Stdout     []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr     []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Exitcode   int32  `protobuf:"varint,3,opt,name=exitcode" json:"exitcode,omitempty"`
	PayloadUrl string `protobuf:"bytes,4,opt,name=payloadUrl" json:"payloadUrl,omitempty"`
	Id         uint64 `protobuf:"varint,5,opt,name=id" json:"id,omitempty"`
	Module     string `protobuf:"bytes,6,opt,name=module" json:"module,omitempty"`
}

func (m *BinReply) Reset()                    { *m = BinReply{} }
func (m *BinReply) String() string            { return proto.CompactTextString(m) }
func (*BinReply) ProtoMessage()               {}
func (*BinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Pong struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Meta struct {
	Ping   *EchoRequest   `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
	Cancel *CancelRequest `protobuf:"bytes,2,opt,name=cancel" json:"cancel,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Meta) GetPing() *EchoRequest {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Meta) GetCancel() *CancelRequest {
	if m != nil {
		return m.Cancel
	}
	return nil
}

type EchoRequest struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Payload        []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type EchoResponse struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Payload        []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CancelRequest struct {
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
}

func (m *CancelRequest) Reset()                    { *m = CancelRequest{} }
func (m *CancelRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()               {}
func (*CancelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*BinRequest)(nil), "babl.BinRequest")
	proto.RegisterType((*BinReply)(nil), "babl.BinReply")
	proto.RegisterType((*Empty)(nil), "babl.Empty")
	proto.RegisterType((*Pong)(nil), "babl.Pong")
	proto.RegisterType((*Meta)(nil), "babl.Meta")
	proto.RegisterType((*EchoRequest)(nil), "babl.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "babl.EchoResponse")
	proto.RegisterType((*CancelRequest)(nil), "babl.CancelRequest")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0xab, 0xd4, 0x30,
	0x14, 0xa5, 0x9d, 0x74, 0xde, 0xcc, 0x9d, 0x79, 0x4f, 0x8d, 0x22, 0xf1, 0x81, 0x32, 0x14, 0xc4,
	0xc2, 0x83, 0x2e, 0x46, 0x10, 0x71, 0xa9, 0x74, 0xe1, 0x42, 0x91, 0x80, 0x1b, 0x37, 0xcf, 0xb4,
	0x09, 0xcf, 0x62, 0x9a, 0xd4, 0x34, 0x2d, 0xf6, 0xcf, 0xf8, 0x97, 0xfc, 0x4b, 0x92, 0x8f, 0xea,
	0x28, 0xba, 0x74, 0x97, 0x73, 0xee, 0xb9, 0xf7, 0x9e, 0x73, 0x09, 0x40, 0xc7, 0x5a, 0x55, 0xf6,
	0x46, 0x5b, 0x8d, 0x51, 0xcd, 0x6a, 0x99, 0x7f, 0x4f, 0x00, 0x5e, 0xb6, 0x8a, 0x8a, 0x2f, 0xa3,
	0x18, 0x2c, 0xbe, 0x07, 0xd9, 0x60, 0x79, 0xab, 0x48, 0x72, 0x48, 0x8a, 0x3d, 0x0d, 0x00, 0x5f,
	0xc1, 0x4a, 0xa8, 0x89, 0xa4, 0x87, 0x55, 0xb1, 0x3b, 0x3e, 0x28, 0x5d, 0x63, 0xf9, 0xab, 0xa9,
	0xac, 0xd4, 0x54, 0x29, 0x6b, 0x66, 0xea, 0x54, 0xf8, 0x11, 0x40, 0xcf, 0x66, 0xa9, 0x19, 0x7f,
	0x6f, 0x24, 0x59, 0x1d, 0x92, 0x62, 0x4b, 0x4f, 0x18, 0x7c, 0x01, 0x69, 0xcb, 0x09, 0x3a, 0x24,
	0x05, 0xa2, 0x69, 0xcb, 0xf1, 0x7d, 0x58, 0x77, 0x9a, 0x8f, 0x52, 0x90, 0xcc, 0x6b, 0x23, 0xba,
	0x7c, 0x06, 0x9b, 0x65, 0x30, 0xbe, 0x0d, 0xab, 0xcf, 0x62, 0xf6, 0xa6, 0xb6, 0xd4, 0x3d, 0x9d,
	0xd1, 0x89, 0xc9, 0x51, 0x90, 0xd4, 0x73, 0x01, 0xbc, 0x48, 0x9f, 0x27, 0xf9, 0xb7, 0x04, 0x36,
	0xde, 0x5c, 0x2f, 0x67, 0x37, 0x7c, 0xb0, 0x5c, 0x8f, 0x36, 0x06, 0x8a, 0x28, 0xf2, 0xc2, 0x18,
	0xdf, 0x1f, 0x78, 0x61, 0x0c, 0xbe, 0x84, 0x8d, 0xf8, 0xda, 0xda, 0x46, 0x73, 0xe1, 0xad, 0x67,
	0xf4, 0x27, 0xfe, 0x23, 0x18, 0xfa, 0x47, 0xb0, 0xec, 0x2f, 0xc1, 0xd6, 0xa7, 0xc1, 0xf2, 0x33,
	0xc8, 0xaa, 0xae, 0xb7, 0x73, 0x4e, 0x00, 0xbd, 0xd3, 0xea, 0xc6, 0xa5, 0x9b, 0x98, 0x5c, 0xd2,
	0x4d, 0x4c, 0xe6, 0x1f, 0x00, 0xbd, 0x11, 0x96, 0xe1, 0xc7, 0x80, 0xfa, 0x56, 0xdd, 0xf8, 0xd2,
	0xee, 0x78, 0x27, 0x5c, 0xbe, 0x6a, 0x3e, 0xe9, 0x78, 0x7a, 0xea, 0xcb, 0xf8, 0x0a, 0xd6, 0x0d,
	0x53, 0x8d, 0x90, 0x3e, 0xcd, 0xee, 0x78, 0x37, 0x08, 0x5f, 0x79, 0x6e, 0x91, 0x46, 0x49, 0xfe,
	0x11, 0x76, 0x27, 0x13, 0xa2, 0xeb, 0xb0, 0xdb, 0xb9, 0x7e, 0x02, 0xb7, 0x06, 0x57, 0x52, 0x8d,
	0xb8, 0x56, 0x63, 0x57, 0x8b, 0x70, 0xa2, 0x73, 0x7a, 0xb1, 0xd0, 0x6f, 0x3d, 0x8b, 0x09, 0x9c,
	0xc5, 0xf0, 0xfe, 0x52, 0x7b, 0xba, 0xc0, 0x9c, 0xc1, 0x3e, 0x6c, 0x18, 0x7a, 0xad, 0x06, 0xf1,
	0x3f, 0x56, 0x94, 0x70, 0xfe, 0x5b, 0x3a, 0xfc, 0x10, 0xc0, 0x84, 0xe7, 0x75, 0xdc, 0x85, 0xe8,
	0x36, 0x32, 0xaf, 0x79, 0xbd, 0xf6, 0x7f, 0xfe, 0xe9, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0x63, 0x6a, 0x25, 0x01, 0x03, 0x00, 0x00,
}
